chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('chat/<str:username>/', views.room, name='room'),
]

chat_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('user/<str:username>/', views.profile_view, name='profile'),
    path('user/update/<str:username>/', views.profile_edit, name='edit-profile'),
    path('user/delete/<str:username>/', views.user_delete, name='user-delete'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ChatMessage(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    content = models.TextField(null=True, blank=True)
    thread_name = models.CharField(null=True, blank=True, max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    @classmethod
    def create(cls, username, content, thread_name):
        sender = User.objects.get(username=username)
        ChatMessage.objects.create(sender=sender, content=content, thread_name=thread_name)


class Notification(models.Model):
    sender = models.ForeignKey(User, related_name='sender_notifications', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='receiver_notifications', on_delete=models.CASCADE)
    seen = models.BooleanField(default=False)

    @classmethod
    def create(cls, sender, receiver):
        Notification.objects.create(sender_id=sender, receiver_id=receiver)

    @classmethod
    def mark_as_not_seen(cls, sender, receiver):
        notification = Notification.objects.get(sender_id=sender, receiver_id=receiver)
        notification.seen = False
        notification.save()

    @classmethod
    def mark_as_seen(cls, sender, receiver):
        if Notification.objects.filter(sender_id=sender, receiver_id=receiver).exists():
            notification = Notification.objects.get(sender_id=sender, receiver_id=receiver)
            notification.seen = True
            notification.save()

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    city = models.CharField(max_length=100, null=True)
    is_online = models.BooleanField(default=False)
    profile_image = models.ImageField(upload_to='images/')

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('There is registered user with given e-mail')
        return self.cleaned_data['email']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ["city", "profile_image"]


class UserEditForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists() and self.instance.email != email:
            raise forms.ValidationError('There is registered user with given e-mail')
        return self.cleaned_data['email']

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from chat.models import ChatMessage, Notification


@login_required
def index_view(request):
    users = User.objects.exclude(username=request.user.username)

    user = request.user
    notifications = Notification.objects.filter(receiver_id=user.id, seen=False)
    notifications_sender_id = [n.sender_id for n in notifications]

    context = {"users": users, "notifications_id": notifications_sender_id}
    return render(request, "chat/index.html", context)


@login_required
def room(request, username):

    if request.user.username == username:
        return redirect('chat:index')

    receiver_user = User.objects.get(username=username)
    users = User.objects.exclude(username=request.user.username)

    user = request.user
    notifications = Notification.objects.filter(receiver_id=user.id, seen=False)
    notifications_sender_id = [n.sender_id for n in notifications]

    if request.user.id > receiver_user.id:
        thread_name = f'chat_{request.user.id}-{receiver_user.id}'
    else:
        thread_name = f'chat_{receiver_user.id}-{request.user.id}'

    messages = ChatMessage.objects.filter(thread_name=thread_name)
    context = {"users": users, "receiver_user": receiver_user, "chat_messages": messages, "notifications_id": notifications_sender_id}
    return render(request, 'chat/room.html', context)

users/views.py
from django.shortcuts import render, get_object_or_404
from users.forms import UserRegisterForm, ProfileForm, UserEditForm
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.dispatch import receiver
from django.contrib.auth.models import User


@receiver(user_logged_in)
def got_online(user, request, **kwargs):
    user.profile.is_online = True
    user.profile.save()


@receiver(user_logged_out)
def got_offline(user, request, **kwargs):
    user.profile.is_online = False
    user.profile.save()


def register(request):
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, 'You are successfully registered! You can log in now.')
            return redirect(reverse('users:login'))
    else:
        user_form = UserRegisterForm()
        profile_form = ProfileForm()

    context = {'user_form': user_form, "profile_form": profile_form}

    return render(request, 'users/register.html', context)


def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    context = {'user': user}
    return render(request, 'users/profile_view.html', context)


def profile_edit(request, username):
    user = get_object_or_404(User, username=username)

    user_form = UserEditForm(instance=user)
    profile_form = ProfileForm(instance=user.profile)

    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('users:profile', user.username)
    context = {'user_form': user_form, 'profile_form': profile_form}

    return render(request, 'users/profile_update.html', context)


def user_delete(request, username):
    user = get_object_or_404(User, username=username)
    if request.method == 'POST':
        user.delete()
        messages.warning(request, 'User has been deleted')
    return redirect(reverse('chat:index'))

chat/templates/chat/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap stuff -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


    <!-- CHAT STYLE -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "chat:index" %}">Home Page</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--- Pozycje nawigacji -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav me-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "users:profile" request.user.username %}">Your profile</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="d-flex ml-0 navbar-nav">
                {% if  request.user.is_authenticated %}
                    <li class="nav-item">
                        <span class="d-inline-block nav-link text-white">Logged as {{ request.user.username }}</span>
                    </li>
                    <li class="nav-item"><a href="{% url "users:logout" %}" class="nav-link d-inline-block">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url "users:login" %}" class="border border-1 rounded-2 px-2 nav-link">
                            <span style="color: white;">Log in</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if messages %}
        <ul class="messages list-unstyled position-fixed col-12" id="msg" style="z-index: 1;">
            {% for message in messages %}
                <li class="message">
                    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

<div class="container fluid">
    {% block content %}
    {% endblock %}
</div>



{% block scripts %}{% endblock %}
</body>
</html>

chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block title %}Chat room{% endblock %}

{% block content %}

    <div class="row mt-3">
        <!-- USERS -->
        <div class="col-lg-3" id="accordion">
            <div class="card mt-3">
                <div class="card-header d-flex justify-content-between align-items-center p-3" style="border-bottom: none;">
                    <a class="btn p-0" data-bs-toggle="collapse" href="#collapseUsers">
                        <h5 class="mb-0">Users</h5>
                    </a>
                </div>
            </div>
            <!-- USERS LIST -->
            <div id="collapseUsers" class="collapse show" data-bs-parent="#accordion">
                <ul class="list-group list-group-flush list-unstyled mb-0" id="user-ul">
                  {% for user in users %}
                      <li class="p-2 border-bottom mb-0 user-li">
                      <a href="{% url 'chat:room' username=user.username %}" class="d-flex justify-content-between user-list-link" id="user-link-{{ user.id }}">
                          <div class="d-flex flex-row">
                            <div class="user-list-image">
                              <img
                                src="{{ user.profile.profile_image.url }}"
                                alt="avatar" class="d-flex align-self-center me-3" width="60" style="border-radius: 50%;">

                                {% if user.profile.is_online %}
                                  <span class="online-status badge bg-success badge-dot p-2 border border-light rounded-circle">
                                      <span class="visually-hidden">Status</span>
                                  </span>
                                {% else %}
                                  <span class="online-status badge bg-danger badge-dot p-2 border border-light rounded-circle">
                                      <span class="visually-hidden">Status</span>
                                  </span>
                                {% endif %}
                            </div>
                            <div class="pt-1 user-list-info">
                              <p class="fw-bold mb-0">{{ user.username }}</p>
                                <span id="notification_{{ user.id }}">
                                    {% if user.id in notifications_id %}
                                        <span class="badge rounded-pill bg-success" id="notification_{{ user.id }}">New messages</span>
                                    {% else %}
                                        <span class="badge rounded-pill bg-secondary" id="notification_{{ user.id }}">No new messages</span>
                                    {% endif %}
                                </span>

                            </div>
                          </div>
                        </a>
                      </li>
                  {% endfor %}
              </ul>
            </div>
        </div>

            <!-- END USERS LIST -->
        <!-- END USERS -->

        <!-- CHAT -->
        <div class="col-lg-9">
            <div class="card mt-3" id="chat2">
                <div class="card-header d-flex justify-content-between align-items-center p-3">
                    <h5 class="mb-0">Chat</h5>
                </div>
                <div id="chat-log" class="card-body" data-mdb-perfect-scrollbar="true"
                     style="position: relative; height: 400px">
                    <p>Select user to start chat</p>
                </div>
                <div class="card-footer text-muted d-flex justify-content-start align-items-center p-3">
                    <div class="mx-3">
                        <input id="chat-message-input" type="text" size="100" class="form-control form-control-lg" placeholder="Type message">
                    </div>
                    <div class="ml-3">
                        <input id="chat-message-submit" type="button" value="Send" class="btn btn-success disabled">
                    </div>
                </div>
            </div>
        </div>
        <!-- END CHAT -->
    </div>
{% endblock %}

{% block scripts %}

    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        const url = 'ws://' + window.location.host + '/ws/chat/' + roomName + '/';
        const chatSocket = new WebSocket(url);

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            const dateOptions = {hour: 'numeric', minute: 'numeric', hour12: true};
            const datetime = new Date(data.datetime).toLocaleString('en', dateOptions);
            const isMe = data.user === '{{ request.user }}';
            const name = isMe ? 'Me' : data.user;
            const message = data.message;

            const $chat = $('#chat-log');

            if (isMe === true) {
                $chat.append(
                    "<div class=\"d-flex flex-row justify-content-start\">" +
                    "<p class=\"small ms-3 mb-3 rounded-3 text-muted\">" + name + "</p>" +
                    "<div><p class=\"small p-2 ms-3 mb-1 rounded-3\" style=\"background-color: #f5f6f7;\">" + message + "</p>" +
                    "<p class=\"small ms-3 mb-3 rounded-3 text-muted\">" + datetime + "</p>" + "</div></div>"
                );
            } else {
                $chat.append(
                    "<div class=\"d-flex flex-row justify-content-end\">" +
                    "<p class=\"small ms-3 mb-3 rounded-3 text-muted\">" + name + "</p>" +
                    "<div><p class=\"small p-2 ms-3 mb-1 rounded-3 bg-primary text-white\" style=\"background-color: #f5f6f7;\">" + message + "</p>" +
                    "<p class=\"small ms-3 mb-3 rounded-3 text-muted\">" + datetime + "</p>" + "</div></div>");
            }

            $chat.scrollTop($chat[0].scrollHeight);
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock %}

chat/templates/chat/room.html
{% extends "chat/base.html" %}

{% block title %}Chat room{% endblock %}
{% load static %}

{% block content %}
    {{ room_name|json_script:"room-name" }}

    <div class="row mt-3">
        <!-- USERS -->
        <div class="col-lg-4" id="accordion">
            <div class="card mt-3">
                <div class="card-header d-flex justify-content-between align-items-center p-3" style="border-bottom: none;">
                    <a class="btn p-0" data-bs-toggle="collapse" href="#collapseUsers">
                        <h5 class="mb-0">Users</h5>
                    </a>
                </div>
            </div>
            <!-- USERS LIST -->

            <div id="collapseUsers" class="collapse show" data-bs-parent="#accordion">
                <ul class="list-group list-group-flush list-unstyled mb-0" id="user-ul">
                  {% for user in users %}
                      <li class="p-2 border-bottom mb-0 user-li">
                      <a href="{% url 'chat:room' username=user.username %}" class="d-flex justify-content-between user-list-link" id="user-link-{{ user.id }}">
                          <div class="d-flex flex-row">
                            <div class="user-list-image">
                              <img
                                src="{{ user.profile.profile_image.url }}"
                                alt="avatar" class="d-flex align-self-center me-3" width="60" style="border-radius: 50%;">

                                {% if user.profile.is_online %}
                                  <span class="online-status badge bg-success badge-dot p-2 border border-light rounded-circle">
                                      <span class="visually-hidden">Status</span>
                                  </span>
                                {% else %}
                                  <span class="online-status badge bg-danger badge-dot p-2 border border-light rounded-circle">
                                      <span class="visually-hidden">Status</span>
                                  </span>
                                {% endif %}
                            </div>
                            <div class="pt-1 user-list-info">
                              <p class="fw-bold mb-0">{{ user.username }}</p>
                                <span id="notification_{{ user.id }}">
                                    {% if user.id in notifications_id %}
                                        <span class="badge rounded-pill bg-success" id="notification_{{ user.id }}">New messages</span>
                                    {% else %}
                                        <span class="badge rounded-pill bg-secondary" id="notification_{{ user.id }}">No new messages</span>
                                    {% endif %}
                                </span>

                            </div>
                          </div>
                        </a>
                      </li>
                  {% endfor %}
              </ul>
            </div>
        </div>
            <!-- END USERS LIST -->
        <!-- END USERS -->

        <!-- CHAT -->
        <div class="col-lg-8">
            <div class="card mt-3" id="chat2">
                <div class="card-header d-flex align-items-center p-3">
                    <img src="{{ receiver_user.profile.profile_image.url }}" alt="avatar" class="d-flex" width="45" style="border-radius: 50%;">
                    <a href="{% url 'users:profile' receiver_user.username %}" class="profile-link"><h5 class="mb-0" style="margin-left: 20px;">{{ receiver_user.username }}</h5></a>
                    {% if receiver_user.profile.is_online %}
                        <span class="badge bg-success badge-dot p-2 border border-light rounded-circle" style="margin-left: 10px;">
                            <span class="visually-hidden">Status</span>
                        </span>
                    {% else %}
                        <span class="badge bg-danger badge-dot p-2 border border-light rounded-circle" style="margin-left: 10px;">
                            <span class="visually-hidden">Status</span>
                        </span>
                    {% endif %}
                </div>
                <div id="chat-log" class="card-body" data-mdb-perfect-scrollbar="true"
                     style="position: relative; height: 400px">
                    <!-- PLACE FOR MESSAGES -->
                    {% for message in chat_messages %}
                        {% if message.sender.username == request.user.username %}
                            <div class="d-flex flex-row justify-content-end">
                                <div>
                                    <p class="small p-2 ms-3 mb-1 rounded-3 bg-primary text-white" style="margin-right: 10px; margin-top: 5px;">{{ message }}</p>
                                    <p class="small rounded-3 text-muted ms-3 mb-1" style="float: right; margin-right: 10px;">{{ message.timestamp|time:'H:i' }}</p>
                                </div>
                            <img src="{{ request.user.profile.profile_image.url }}" alt="avatar 1" style="width: 45px; height: 100%; border-radius: 50%;">
                            </div>
                        {% else %}
                            <div class="d-flex flex-row justify-content-start">
                            <img src="{{ receiver_user.profile.profile_image.url }}" alt="avatar 1" style="width: 45px; height: 100%; border-radius: 50%;">
                                <div>
                                    <p class="small p-2 ms-3 mb-1 rounded-3" style="background-color: #f5f6f7; margin-top: 5px;">{{ message }}</p>
                                    <p class="small ms-3 mb-3 rounded-3 text-muted">{{ message.timestamp|time:'H:i' }}</p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="card-footer text-muted d-flex justify-content-start align-items-center p-3">
                    <div class="mx-3">
                        <input id="chat-message-input" type="text" size="100" class="form-control form-control-lg" placeholder="Type message">
                    </div>
                    <div class="ml-3">
                        <input id="chat-message-submit" type="button" value="Send" class="btn btn-success">
                    </div>

                </div>
            </div>
        </div>
        <!-- END CHAT -->
    </div>


    {{ receiver_user.id|json_script:"json-username" }}
    {{ request.user.username|json_script:"json-message-username" }}
    {{ request.user.profile.profile_image.url|json_script:"json-user-image" }}
    {{ receiver_user.profile.profile_image.url|json_script:"json-receiver-image" }}
{% endblock %}

{% block scripts %}

    <script>
        window.onload = function() {
            const $chat = $("#chat-log");
            $chat.scrollTop($chat[0].scrollHeight);
        }
    </script>

    <script>
        const receiverId = JSON.parse(document.getElementById('json-username').textContent);
        const url = 'ws://' + window.location.host + '/ws/' + receiverId + '/';
        const chatSocket = new WebSocket(url);

        chatSocket.onmessage = function (e) {
            console.log(e.data);
            const data = JSON.parse(e.data);
            const dateOptions = {hour: 'numeric', minute: 'numeric', hour12: false};
            const datetime = new Date(data.datetime).toLocaleString('pl', dateOptions);
            const isMe = data.user === '{{ request.user }}';
            const name = isMe ? 'Me' : data.user;
            const message = data.message;
            const userImage = '{{ request.user.profile.profile_image.url }}';
            const receiverImage = '{{ receiver_user.profile.profile_image.url }}';

            const $chat = $('#chat-log');

            if (isMe === true) {
                $chat.append(
                    "<div class=\"d-flex flex-row justify-content-end\">" +
                    "<div><p class=\"small p-2 ms-3 mb-1 rounded-3 bg-primary text-white\" style=\"margin-right: 10px; margin-top: 5px;\">" + message + "</p>" +
                    "<p class=\"small ms-3 mb-3 rounded-3 text-muted\" style=\"float: right; margin-right: 10px;\">" + datetime + "</p>" + "</div>" +
                    "<img src=\"" + userImage + "\"" + "alt=\"avatar 1\" style=\"width: 45px; height: 100%;  border-radius: 50%;\">" +
                    "</div>"
                );
            } else {
                $chat.append(
                    "<div class=\"d-flex flex-row justify-content-start\">" +
                    "<img src=\"" + receiverImage + "\"" + "alt=\"avatar 1\" style=\"width: 45px; height: 100%; border-radius: 50%;\">" +
                    "<div><p class=\"small p-2 ms-3 mb-1 rounded-3\" style=\"background-color: #f5f6f7; margin-top: 5px;\">" + message + "</p>" +
                    "<p class=\"small ms-3 mb-3 rounded-3 text-muted\">" + datetime + "</p>" + "</div></div>");
            }

            $chat.scrollTop($chat[0].scrollHeight);

            if (data.sender_id !== {{ request.user.id }}){
                let notification_sender_id = '#notification_' + data.sender_id;
                $(notification_sender_id).html(
                    "<span class=\"badge rounded-pill bg-success\">New messages</span>"
                );
            }
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'sender': {{ request.user.id }},
                'receiver': {{ receiver_user.id }}
            }));
            messageInputDom.value = '';
        };

        $(document).ready(function(){
            const receiverId = JSON.parse(document.getElementById('json-username').textContent);
            let notification_receiver_id = '#notification_' + receiverId;
                $(notification_receiver_id).html(
                    "<span class=\"badge rounded-pill bg-secondary\">No new messages</span>"
                );

            chatSocket.onopen = () => chatSocket.send(JSON.stringify({
                'type': 'notification',
                'from': {{ receiver_user.id }},
                'to': {{ request.user.id }}
            }));
        });
    </script>
{% endblock %}

users/templates/users/profile_view.html
{% extends "chat/base.html" %}

{% block title %}{{ user.username }} profile{% endblock %}

{% block content %}
    <div class="card mt-3" style="width:300px">
        <img class="card-img-top" src="{{ user.profile.profile_image.url }}">
        <div class="card-body">
            <h4 class="card-title">{{ user.username }}</h4>
            <p class="card-text mb-2">Name: {{ user.first_name }} {{ user.last_name }}</p>
            <p class="card-text mb-2">E-mail: {{ user.email }}</p>
            <p class="card-text">City: {{ user.profile.city }}</p>

            {% if request.user == user %}
                <a href="{% url 'users:edit-profile' user.username %}" class="btn btn-warning mt-2">Update profile</a>
            {% else %}
                <a href="{% url 'chat:room' user.username %}" class="btn btn-primary">Chat with {{ user.username }}</a>
            {% endif %}

            {% if request.user.is_superuser or request.user == user%}
                <form method="post" action="{% url "users:user-delete" user.username %}" class="m-0 p-0">
                    {% csrf_token %}
                    <input class="btn btn-danger mt-3" value="Delete user" type="submit"
                            onclick="return confirm('Do you want to delete this user?');">
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}